# Generated by Django 4.2.30 on 2026-04-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0002_purchaseinvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_categories', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'account categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_group', models.BooleanField(default=False)),
                ('root_type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity')], max_length=16)),
                ('report_type', models.CharField(blank=True, choices=[('Balance Sheet', 'Balance Sheet'), ('Profit and Loss', 'Profit and Loss')], max_length=32)),
                ('account_type', models.CharField(blank=True, choices=[('', '—'), ('Accumulated Depreciation', 'Accumulated Depreciation'), ('Asset Received But Not Billed', 'Asset Received But Not Billed'), ('Bank', 'Bank'), ('Cash', 'Cash'), ('Chargeable', 'Chargeable'), ('Capital Work in Progress', 'Capital Work in Progress'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Current Asset', 'Current Asset'), ('Current Liability', 'Current Liability'), ('Depreciation', 'Depreciation'), ('Direct Expense', 'Direct Expense'), ('Direct Income', 'Direct Income'), ('Equity', 'Equity'), ('Expense Account', 'Expense Account'), ('Expenses Included In Asset Valuation', 'Expenses Included In Asset Valuation'), ('Expenses Included In Valuation', 'Expenses Included In Valuation'), ('Fixed Asset', 'Fixed Asset'), ('Income Account', 'Income Account'), ('Indirect Expense', 'Indirect Expense'), ('Indirect Income', 'Indirect Income'), ('Liability', 'Liability'), ('Payable', 'Payable'), ('Receivable', 'Receivable'), ('Round Off', 'Round Off'), ('Round Off for Opening', 'Round Off for Opening'), ('Stock', 'Stock'), ('Stock Adjustment', 'Stock Adjustment'), ('Stock Received But Not Billed', 'Stock Received But Not Billed'), ('Service Received But Not Billed', 'Service Received But Not Billed'), ('Tax', 'Tax'), ('Temporary', 'Temporary')], max_length=64)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('freeze_account', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('balance_must_be', models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=8)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0)),
                ('rgt', models.PositiveIntegerField(db_index=True, default=0)),
                ('old_parent', models.CharField(blank=True, max_length=255)),
                ('include_in_gross', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='finance.accountcategory')),
                ('account_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.currency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.company')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_accounts', to='finance.account')),
            ],
            options={
                'verbose_name_plural': 'accounts',
                'ordering': ['company', 'account_number', 'account_name'],
                'indexes': [models.Index(fields=['company', 'parent_account'], name='finance_acc_company_6f6921_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'account_name'), name='finance_account_company_account_name_uniq'),
        ),
    ]
