# Generated by Django 4.2.30 on 2026-04-21 08:57

from django.db import migrations, models
import django.db.models.deletion


def copy_currencies_to_core(apps, schema_editor):
    FinanceCurrency = apps.get_model('finance', 'Currency')
    CoreCurrency = apps.get_model('core', 'Currency')
    for fc in FinanceCurrency.objects.all():
        CoreCurrency(pk=fc.pk, code=fc.code, name=fc.name).save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_to_core'),
        ('finance', '0003_account_currency_accountcategory'),
    ]

    operations = [
        migrations.RunPython(copy_currencies_to_core, noop_reverse),
        migrations.AlterField(
            model_name='account',
            name='account_currency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='accounts',
                to='core.currency',
            ),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
