# Generated by Django 4.2.30 on 2026-04-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_currency_to_core'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_category',
        ),
        migrations.DeleteModel(
            name='AccountCategory',
        ),
    ]
