# Generated by Django 4.2.30 on 2026-04-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currency_erpnext_fields'),
        ('finance', '0005_remove_account_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center_name', models.CharField(max_length=255)),
                ('cost_center_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_group', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, default=0)),
                ('rgt', models.PositiveIntegerField(db_index=True, default=0)),
                ('old_parent', models.CharField(blank=True, max_length=255)),
                ('disabled', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='core.company')),
                ('parent_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_cost_centers', to='finance.costcenter')),
            ],
            options={
                'verbose_name': 'cost center',
                'verbose_name_plural': 'cost centers',
                'ordering': ['company', 'cost_center_number', 'cost_center_name'],
                'indexes': [models.Index(fields=['company', 'parent_cost_center'], name='finance_cos_company_6925c3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('company', 'cost_center_name'), name='finance_costcenter_company_cost_center_name_uniq'),
        ),
    ]
