# Generated by Django 4.2.30 on 2026-04-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_to_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date_format', models.CharField(blank=True, help_text='Python/strftime-style or locale date pattern used for this country.', max_length=64)),
                ('time_format', models.CharField(blank=True, default='HH:mm:ss', max_length=32)),
                ('time_zones', models.TextField(blank=True, help_text='Typical time zones for this country (e.g. one IANA id per line).')),
                ('code', models.CharField(db_index=True, help_text="The country's ISO 3166-1 alpha-2 code (two letters).", max_length=2, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['country_name'],
            },
        ),
    ]
